# Generated by Django 5.2.8 on 2025-11-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='product_cat_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', '-created_at'], name='product_avail_date_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_available'], name='product_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_best_seller', 'is_available'], name='product_bestseller_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new', '-created_at'], name='product_new_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_top_rated', 'is_available'], name='product_toprated_idx'),
        ),
    ]
